#!/bin/bash
# UNAUTHORITY (UAT) - VALIDATOR SETUP SCRIPT v2.0
# Automatically configures 3 validator nodes with unique addresses from genesis

set -e

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GENESIS_CONFIG="${PROJECT_ROOT}/genesis/genesis_config.json"
NODE_DATA_DIR="${PROJECT_ROOT}/node_data"

echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║  UNAUTHORITY VALIDATOR SETUP                              ║"
echo "║  Setting up 3 Bootstrap Validators with unique addresses  ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Step 1: Verify genesis_config.json exists
if [ ! -f "$GENESIS_CONFIG" ]; then
    echo "❌ ERROR: genesis_config.json not found!"
    echo "   Run: cargo run -p genesis"
    exit 1
fi

echo "✅ Genesis config found: $GENESIS_CONFIG"
echo ""

# Step 2: Extract validator addresses from genesis
echo "📌 Extracting validator addresses from genesis..."

VALIDATOR_1_ADDR=$(jq -r '.bootstrap_nodes[0].address' "$GENESIS_CONFIG")
VALIDATOR_2_ADDR=$(jq -r '.bootstrap_nodes[1].address' "$GENESIS_CONFIG")
VALIDATOR_3_ADDR=$(jq -r '.bootstrap_nodes[2].address' "$GENESIS_CONFIG")

VALIDATOR_1_STAKE=$(jq -r '.bootstrap_nodes[0].stake_void' "$GENESIS_CONFIG")
VALIDATOR_2_STAKE=$(jq -r '.bootstrap_nodes[1].stake_void' "$GENESIS_CONFIG")
VALIDATOR_3_STAKE=$(jq -r '.bootstrap_nodes[2].stake_void' "$GENESIS_CONFIG")

VALIDATOR_1_PRIVKEY=$(jq -r '.bootstrap_nodes[0].private_key' "$GENESIS_CONFIG")
VALIDATOR_2_PRIVKEY=$(jq -r '.bootstrap_nodes[1].private_key' "$GENESIS_CONFIG")
VALIDATOR_3_PRIVKEY=$(jq -r '.bootstrap_nodes[2].private_key' "$GENESIS_CONFIG")

if [ -z "$VALIDATOR_1_ADDR" ] || [ "$VALIDATOR_1_ADDR" == "null" ]; then
    echo "❌ ERROR: Failed to extract bootstrap node addresses from genesis!"
    exit 1
fi

echo "   ✓ Validator-1: ${VALIDATOR_1_ADDR:0:30}... (${VALIDATOR_1_STAKE} VOI)"
echo "   ✓ Validator-2: ${VALIDATOR_2_ADDR:0:30}... (${VALIDATOR_2_STAKE} VOI)"
echo "   ✓ Validator-3: ${VALIDATOR_3_ADDR:0:30}... (${VALIDATOR_3_STAKE} VOI)"
echo ""

# Step 3: Create node directories
echo "📌 Creating validator node directories..."

for i in 1 2 3; do
    DIR="${NODE_DATA_DIR}/validator-$i"
    mkdir -p "$DIR"/{blockchain,logs}
    echo "   ✓ Created: $DIR"
done

echo ""

# Step 4: Generate validator.toml configs per node
echo "📌 Generating validator.toml configs..."

for i in 1 2 3; do
    DIR="${NODE_DATA_DIR}/validator-$i"
    
    # Get address untuk validator ini
    case $i in
        1) ADDR=$VALIDATOR_1_ADDR; STAKE=$VALIDATOR_1_STAKE; PRIVKEY=$VALIDATOR_1_PRIVKEY; SENTRY_PORT=30333; SIGNER_PORT=30331 ;;
        2) ADDR=$VALIDATOR_2_ADDR; STAKE=$VALIDATOR_2_STAKE; PRIVKEY=$VALIDATOR_2_PRIVKEY; SENTRY_PORT=30334; SIGNER_PORT=30332 ;;
        3) ADDR=$VALIDATOR_3_ADDR; STAKE=$VALIDATOR_3_STAKE; PRIVKEY=$VALIDATOR_3_PRIVKEY; SENTRY_PORT=30335; SIGNER_PORT=30333 ;;
    esac
    
    # Generate PSK for sentry-validator tunnel
    PSK=$(openssl rand -hex 32)
    
    # Save private key to file
    echo "$PRIVKEY" > "$DIR/private_key.hex"
    chmod 600 "$DIR/private_key.hex"
    
    # Create validator.toml
    cat > "$DIR/validator.toml" <<EOF
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# UNAUTHORITY (UAT) - VALIDATOR CONFIGURATION v2.0
# Auto-generated by setup_validators.sh
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

[validator]
node_id = "validator-$i"
address = "$ADDR"
private_key_path = "private_key.hex"
stake_void = $STAKE

# Rewards
auto_claim_rewards = true

# Slashing penalties
double_signing_slash = 100  # 100% + ban
downtime_slash = 1          # 1% per epoch

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# SENTRY NODE ARCHITECTURE
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

[sentry_public]
listen_addr = "0.0.0.0"
listen_port = $SENTRY_PORT
max_connections = 100

[sentry_private]
listen_addr = "127.0.0.1"
listen_port = $SIGNER_PORT
psk = "$PSK"

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# NETWORK
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

[network]
bootstrap_nodes = [
    "127.0.0.1:30333",
    "127.0.0.1:30334",
    "127.0.0.1:30335"
]

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# API
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

[api]
enabled = true
listen_addr = "127.0.0.1"
rest_port = $((8080 + i - 1))
grpc_port = $((50051 + i - 1))
api_key = "dev_key_validator_$i"
EOF

    echo "   ✓ Created: $DIR/validator.toml"
    echo "      - Address: ${ADDR:0:30}..."
    echo "      - Sentry Port: $SENTRY_PORT"
    echo "      - Signer Port: $SIGNER_PORT"
    echo "      - REST API: http://127.0.0.1:$((8080 + i - 1))"
    echo "      - gRPC: 127.0.0.1:$((50051 + i - 1))"
    echo ""
done

# Step 5: Copy genesis config to each validator
echo "📌 Copying genesis config to validators..."

for i in 1 2 3; do
    cp "$GENESIS_CONFIG" "${NODE_DATA_DIR}/validator-$i/genesis_config.json"
    echo "   ✓ Copied to validator-$i"
done

echo ""

# Step 6: Create .env files for each validator
echo "📌 Creating environment files..."

for i in 1 2 3; do
    case $i in
        1) ADDR=$VALIDATOR_1_ADDR ;;
        2) ADDR=$VALIDATOR_2_ADDR ;;
        3) ADDR=$VALIDATOR_3_ADDR ;;
    esac
    
    cat > "${NODE_DATA_DIR}/validator-$i/.env" <<EOF
# Auto-generated environment variables for Validator-$i
export UAT_VALIDATOR_ADDRESS="$ADDR"
export UAT_NODE_ID="validator-$i"
export UAT_DATA_DIR="${NODE_DATA_DIR}/validator-$i"
EOF

    echo "   ✓ Created .env for validator-$i"
done

echo ""

# Step 7: Display startup instructions
echo "╔════════════════════════════════════════════════════════════╗"
echo "║ ✅ VALIDATOR SETUP COMPLETE                               ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "📊 VALIDATOR SUMMARY:"
echo "   • 3 Validators configured"
echo "   • Each with unique address from genesis"
echo "   • Each with 1,000 UAT stake (100,000,000,000 VOI)"
echo "   • Sentry architecture enabled"
echo "   • Private keys saved to private_key.hex (600 permissions)"
echo ""
echo "🚀 TO START VALIDATORS:"
echo ""
echo "   Terminal 1 (Validator-1):"
echo "   $ cd $PROJECT_ROOT"
echo "   $ source node_data/validator-1/.env"
echo "   $ cargo run -p uat-node -- --config node_data/validator-1/validator.toml"
echo ""
echo "   Terminal 2 (Validator-2):"
echo "   $ source node_data/validator-2/.env"
echo "   $ cargo run -p uat-node -- --config node_data/validator-2/validator.toml"
echo ""
echo "   Terminal 3 (Validator-3):"
echo "   $ source node_data/validator-3/.env"
echo "   $ cargo run -p uat-node -- --config node_data/validator-3/validator.toml"
echo ""
echo "⚠️  SECURITY:"
echo "   • Private keys stored in node_data/validator-*/private_key.hex"
echo "   • Never commit private_key.hex to git!"
echo "   • Backup keys to secure cold storage"
echo ""
