#!/bin/bash
#
# QUICK TESTNET LEVEL EXAMPLES
# Shows how to run different testnet levels
#

echo "🎯 UNAUTHORITY GRADUATED TESTNET - QUICK EXAMPLES"
echo ""

echo "==== LEVEL 1: FUNCTIONAL TESTING (Current) ===="
echo "Purpose: UI/API testing, basic functionality"
echo "Command:"
echo "  UAT_TESTNET_LEVEL=functional ./scripts/test_graduated_testnet.sh functional"
echo ""
echo "Features:"
echo "  ✅ Faucet enabled"
echo "  ✅ Immediate finalization (no consensus delay)"
echo "  ✅ Mock burn verification"
echo "  ✅ Flutter wallet testing"
echo ""

echo "==== LEVEL 2: CONSENSUS TESTING (Real BFT) ===="
echo "Purpose: Test real blockchain consensus, oracle aggregation"
echo "Command:"
echo "  UAT_TESTNET_LEVEL=consensus ./scripts/test_graduated_testnet.sh consensus"  
echo ""
echo "Features:"
echo "  ✅ Real aBFT consensus (3-second finality)"
echo "  ✅ Oracle price aggregation (median of validators)"
echo "  ✅ Ed25519 signature validation"
echo "  ✅ Byzantine fault detection"
echo "  ❌ No real economics (testnet tokens)"
echo ""

echo "==== LEVEL 3: PRODUCTION SIMULATION (Mainnet Code) ===="
echo "Purpose: Final validation before mainnet launch"
echo "Command:"
echo "  UAT_TESTNET_LEVEL=production ./scripts/test_graduated_testnet.sh production"
echo ""
echo "Features:"
echo "  ✅ Identical to mainnet code"
echo "  ✅ Real validator economics & staking"
echo "  ✅ Full Byzantine resistance"  
echo "  ✅ Network partition recovery"
echo "  ❌ Only domain differs from mainnet"
echo ""

echo "==== DEVELOPMENT WORKFLOW ===="
echo ""
echo "1. Start with FUNCTIONAL for basic development:"
echo "   UAT_TESTNET_LEVEL=functional cargo run --bin uat-node 3030"
echo ""
echo "2. Move to CONSENSUS when ready to test blockchain logic:"
echo "   UAT_TESTNET_LEVEL=consensus ./scripts/launch_4_validators.sh"
echo ""  
echo "3. Final PRODUCTION simulation before mainnet:"
echo "   UAT_TESTNET_LEVEL=production ./scripts/test_graduated_testnet.sh production"
echo ""

echo "==== MAINNET READINESS GUARANTEE ===="
echo ""
echo "✅ When Level 1 (functional) passes → UI/UX ready"
echo "✅ When Level 2 (consensus) passes → Blockchain logic ready"  
echo "✅ When Level 3 (production) passes → MAINNET READY! 🚀"
echo ""
echo "This ensures: testnet success = mainnet success guarantee"