#!/bin/bash
# ──────────────────────────────────────────────────────────────
# update_network_config.sh
# Reads the current .onion address from Tor hidden service dir
# and updates both Flutter apps' network_config.json assets.
#
# Usage:  ./scripts/update_network_config.sh
# ──────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Tor hidden service directory (created by setup_tor_testnet.sh)
ONION_DIR="${ONION_DIR:-$HOME/uat-testnet-onion}"
HOSTNAME_FILE="$ONION_DIR/hostname"

if [[ ! -f "$HOSTNAME_FILE" ]]; then
  echo "❌ No hidden service found at $HOSTNAME_FILE"
  echo "   Run: brew services restart tor  (with HiddenServiceDir in torrc)"
  exit 1
fi

ONION_ADDR=$(cat "$HOSTNAME_FILE" | tr -d '[:space:]')
echo "🧅 Current .onion: $ONION_ADDR"

CONFIG_TEMPLATE=$(cat <<ENDJSON
{
  "version": 1,
  "comment": "Bootstrap node addresses — AUTO-GENERATED by scripts/update_network_config.sh. DO NOT hardcode in source.",
  "testnet": {
    "bootstrap_nodes": [
      {
        "name": "validator-1",
        "onion": "$ONION_ADDR",
        "rest_port": 80,
        "p2p_port": 4001
      }
    ]
  },
  "mainnet": {
    "bootstrap_nodes": []
  }
}
ENDJSON
)

TARGETS=(
  "$PROJECT_ROOT/flutter_wallet/assets/network_config.json"
  "$PROJECT_ROOT/flutter_validator/assets/network_config.json"
)

for target in "${TARGETS[@]}"; do
  mkdir -p "$(dirname "$target")"
  echo "$CONFIG_TEMPLATE" > "$target"
  echo "✅ Updated: $target"
done

# Also update testnet-tor-info.json at project root
cat > "$PROJECT_ROOT/testnet-tor-info.json" <<ENDJSON2
{
  "network": "testnet",
  "generated_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "bootstrap_nodes": [
    {
      "name": "validator-1",
      "onion": "$ONION_ADDR",
      "rest_url": "http://$ONION_ADDR",
      "p2p": "$ONION_ADDR:4001"
    }
  ],
  "verify": "curl --socks5-hostname 127.0.0.1:9050 http://$ONION_ADDR/health"
}
ENDJSON2
echo "✅ Updated: testnet-tor-info.json"

echo ""
echo "🎉 All config files updated with: $ONION_ADDR"
echo "   Hot-reload your Flutter apps to pick up the change."
